title: Michelle W Zhou
affiliation: Cornell University
email: mwz7@cornell.edu
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
avatar: ./assets/img/Michelle Zhou Fall 2021 Headshot.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://mwz724.github.io
remote_theme: yaoyao-liu/minimal-light
